# Generated by Django 3.2.5 on 2023-06-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230618_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='default_shipping_address',
            field=models.BooleanField(default=False),
        ),
    ]
