# Generated by Django 3.2.5 on 2023-06-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230621_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cardholder_name',
        ),
    ]
