# Generated by Django 3.2.5 on 2023-06-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsales',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
