# Generated by Django 3.2.5 on 2023-06-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_paymentmethod_cardholder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
