# Generated by Django 3.2.5 on 2023-06-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_paymentmethod_cardholder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name',
        ),
    ]
