# Generated by Django 3.2.5 on 2023-06-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230621_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='default',
            new_name='default_payment_method',
        ),
    ]
