# Generated by Django 3.2.5 on 2023-06-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productsales_product'),
        ('store', '0013_rename_default_paymentmethod_default_payment_method'),
    ]

    operations = [
    ]
